### ISSUE TITLE
Project add-on iteration 2

### ISSUE THREAD

**Issue by beingeek** [phamos-eu/Project-Addon#12]
JSON:

- [x] Timesheet  Record JS: add employee Field

- Timesheet  Record JS: billable_percentage default 100

JS:

- Timesheet  Record JS: Employee Field will be auto filled a\if current user is also employee (can be done via Session Defaults. Script not needed)
- When finishing the Timesheet Record via the "Mark Complete" button the DocType is not refreshed/reloaded. so, to show the new data added one has to update manually. Expection: After setting new data via "Mark Complete" the DocType should refresh and show the data.
- Hide project popup to create Timesheet Record

PY:
- When submitting timesheet record should it fetch employee of current user in timesheet ?
- on submit do not set is_billable  field in Timesheet
- When Timesheet Record is submitted the corresponding Timesheet should also be submitted.
- it seems that the % from Timesheet Record is not reflected in Timesheet. In Timesheet we always have 100% not regarding what has been set in Timesheet Record.
- billing_hourson Timesheet Details should be set by multiplying actual hours from Timesheet Record times percent_billable (100/75/50/25/0). The checkbox is_billablecan always be set.

**Comment by wojosc** [comment]
as disussed let's move the further development to the doctype "Timesheet Record" only. And not use the pop-up for now. As changes are still happening on the doctype editing the pop-up doubles our work without us knowing if it is final yet.

Timesheet Record can be quickly created from the connections dashboard for now.

**Comment by wojosc** [comment]
`billing_hours`on Timesheet Details should be set by multiplying actual hours from Timesheet Record times `percent_billable` (100/75/50/25/0)

The checkbox `is_billable`can always be set.
