### ISSUE TITLE
Employee not fetched in default timesheet doctype

### ISSUE THREAD

**Issue by beingeek** [phamos-eu/Project-Addon#14]
When submitting timesheet record should it fetch employee of current user in timesheet ?

**Comment by wojosc** [comment]
as a project manager I submit Timesheet Records of other users of the system. As there is now employee set in Timesheet Record it uses my session default to set the Employee in Timesheet. This is incorrect, as it looks like I did all the work.

We need a link field `employee` in Timesheet Record that is set via session default and thus is already set by the right person who did the work.

Then, when I submit and create the Timesheet that Employee should be used in Timesheet.
![employee in timesheet](https://github.com/phamos-eu/Project-Addon/assets/22279621/91fc893d-c479-42c9-b9b0-671a977f0917)

**Comment by wojosc** [comment]
thank you @beingeek have tested and will merge to `version-14`
