### ISSUE TITLE
is_billable and billing_hours field set

### ISSUE THREAD

**Issue by beingeek** [phamos-eu/Project-Addon#22]
When submitting 'Timesheet Record' Entry, the posted entry of 'Timesheet' should have is_billable checked and billing_hours set is set to factor of percent_billable * hours spent on 'Timesheet Record'

![image](https://github.com/phamos-eu/Project-Addon/assets/25414115/252e1aec-4c8d-4aba-8b87-a6a9a0e9ffa6)

![image](https://github.com/phamos-eu/Project-Addon/assets/25414115/3a04964f-d0c7-45bb-a0b3-b1592e30bb2c)

In above case billing_hours will be 2 as percent_billable is 100%. In a scenario where percent_billable is 0% is_billable will be unchecked and billing_hours will 0

**Comment by wojosc** [comment]
@beingeek please review your post. Your first screenshot show 50% percent billable which would result in one hour...

**Comment by beingeek** [comment]
Yes @wojosc  you're right and its like this because its issue related to problem. Will post accurate one in pull request
